### ISSUE TITLE
Stream closed exception on Java 1.8 when piping input stream

### ISSUE THREAD

**Issue by nwolfe** [zeroturnaround/zt-exec#30]
Using zt-exec 1.8 and Java 1.8 I'm getting the following error when trying to do `echo foo | /bin/true`:
```
2016-01-27 14:32:51,780 ERROR [Thread-0] [o.z.e.s.StreamPumper] Got exception while closing exhausted output stream
java.io.IOException: Broken pipe
        at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.8.0_71]
        at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[na:1.8.0_71]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_71]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_71]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158) ~[na:1.8.0_71]
        at org.zeroturnaround.exec.stream.StreamPumper.run(StreamPumper.java:137) ~[zt-exec-1.8.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
2016-01-27 14:32:51,783 ERROR [main] [o.z.e.c.StandardProcessCloser] Failed to close process output stream:
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433) ~[na:1.8.0_71]
        at java.io.OutputStream.write(OutputStream.java:116) ~[na:1.8.0_71]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_71]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_71]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158) ~[na:1.8.0_71]
        at org.zeroturnaround.exec.close.StandardProcessCloser.closeStreams(StandardProcessCloser.java:53) [zt-exec-1.8.jar:na]
        at org.zeroturnaround.exec.close.StandardProcessCloser.close(StandardProcessCloser.java:43) [zt-exec-1.8.jar:na]
        at org.zeroturnaround.exec.WaitForProcess.call(WaitForProcess.java:118) [zt-exec-1.8.jar:na]
        at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1007) [zt-exec-1.8.jar:na]
        at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:860) [zt-exec-1.8.jar:na]
        at TryIt.main(TryIt.java:8) [classes/:na]
```

This same error occurs for any program that doesn't read from stdin, such as `/bin/false`, `/bin/ls`, `/bin/pwd`, etc -- this seems to be the difference between success and failure (i.e. no errors when using `/bin/cat` for example).

This only happens on Java 1.8 -- testing on 1.7 works fine.  I have only used zt-exec 1.8 during testing.

I'm having this same error using Apache commons-exec, which is why I started looking for alternatives and come across this library.

Code to reproduce: 
```java
import org.zeroturnaround.exec.ProcessExecutor;
import java.io.ByteArrayInputStream;

public class TryIt {
  public static void main(String[] args) throws Exception {
    ByteArrayInputStream bais = new ByteArrayInputStream("foo".getBytes());
    ProcessExecutor exec = new ProcessExecutor().command("/bin/true");
    int exit = exec.redirectInput(bais).readOutput(true).execute().getExitValue();
    System.out.println(exit);
  }
}
```

Java installation:
```
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
```

**Comment by reinra** [comment]
Thanks for reporting this. I pushed a fix.
You can try it if you build the latest code on your machine.
I'm probably going to release 1.9 also soon.

**Comment by nwolfe** [comment]
@reinra Thank you for the quick reply!  I've learned some things in the meantime.

We just determined that this is some kind of race condition, as opposed to a 100%-reproducible bug. If you use a script like this:
```bash
#!/usr/bin/env sh

exit 0
```
instead of calling /bin/true directly, the exception seems to be thrown significantly less frequently. This leads me to believe that some of the overhead of running the env command and starting another sh in the script above causes some background processing in the JDK to be more likely to have completed before the process exits, and somehow this prevents the exception from being triggered.

**Comment by reinra** [comment]
It makes sense as this error only occurred if JVM couldn't flush the buffer to forked process' stdin before the process was closed. If the process runs longer there's enough time to write into the stdin.

**Comment by AlexanderMakarov** [comment]
Seems like issue wrongly closed.
Because there are no ability to communicate with process STDIN. Original `OutputStream` is closed [here](https://github.com/zeroturnaround/zt-exec/blob/master/src/main/java/org/zeroturnaround/exec/stream/PumpStreamHandler.java#L159). `ProcessExecutor` want to work only with `PumpStreamHandler`, looks like interface `ExecuteStreamHandler` useless in [streams(ExecuteStreamHandler)](https://github.com/zeroturnaround/zt-exec/blob/master/src/main/java/org/zeroturnaround/exec/ProcessExecutor.java#L430).
Helps only custom inheritor of `PumpStreamHandler` with executing `ProcessExecutor` **without** `readOutput`, `redirectOutput`, etc. and **with** `streams(customHandler)`. But in this case library profit goes to zero.

**Comment by AlexanderMakarov** [comment]
>communicate 

I mean exactly "communication", i.e. read process STDOUT and write into its STDIN continuously.
