### ISSUE TITLE
[Thread-5] ERROR com.documents4j.conversion.msoffice.MicrosoftWordBridge - Thread responsible for running script timed 

### ISSUE THREAD

**Issue by waynejaguar** [zeroturnaround/zt-exec#66]
hello,

I have this issue when I run my app

[Thread-5] ERROR com.documents4j.conversion.msoffice.MicrosoftWordBridge - Thread responsible for running script timed out: C:\temp4j\word_start1110703139.vbs
java.util.concurrent.TimeoutException: Timed out waiting for java.lang.ProcessImpl@f2a973b to finish, timeout: 5000 milliseconds, executed command [cmd, /S, /C, ""C:\temp4j\word_start1110703139.vbs""] in directory C:\temp4j, output was 0 bytes:

	at org.zeroturnaround.exec.ProcessExecutor.newTimeoutException(ProcessExecutor.java:1079)
	at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1042)
	at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:860)
	at com.documents4j.conversion.AbstractExternalConverter.runNoArgumentScript(AbstractExternalConverter.java:72)
	at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.runNoArgumentScript(AbstractMicrosoftOfficeBridge.java:51)
	at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.tryStart(AbstractMicrosoftOfficeBridge.java:34)
	at com.documents4j.conversion.msoffice.MicrosoftWordBridge.startUp(MicrosoftWordBridge.java:44)
	at com.documents4j.conversion.msoffice.MicrosoftWordBridge.<init>(MicrosoftWordBridge.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:30)
	at com.documents4j.conversion.ExternalConverterDiscovery.makeAll(ExternalConverterDiscovery.java:42)
	at com.documents4j.conversion.ExternalConverterDiscovery.loadConfiguration(ExternalConverterDiscovery.java:85)
	at com.documents4j.conversion.DefaultConversionManager.<init>(DefaultConversionManager.java:22)
	at com.documents4j.job.LocalConverter.makeConversionManager(LocalConverter.java:78)
	at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:51)
	at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:166)
	at com.sovos.generatorPdf.app.view.PanelView.convertDocxToPdf(PanelView.java:482)
	at com.sovos.generatorPdf.app.view.PanelView$4.run(PanelView.java:541)
	at java.lang.Thread.run(Unknown Source)
 

![imagen](https://user-images.githubusercontent.com/15146873/56974094-2f764280-6b3c-11e9-8f47-3077b70b0cc9.png)

**Comment by waynejaguar** [comment]
I would greatly appreciate your help

**Comment by toomasr** [comment]
I see that the documents4j project is using zt-exec. Not being familiar with the inner workings of documents4j I cannot help you with this issue. Do you mind taking this to https://github.com/documents4j/documents4j and asking for some help there?
